import { useCallback, useEffect, useState } from "react";
import { Trash2, FileText, Eye, Download, MessageSquare } from "lucide-react";
import { reportsApi, type Report, apiText, openProtected } from "@/lib/api";
import { formatDate } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Skeleton } from "@/components/ui/skeleton";

export function ReportsView() {
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [preview, setPreview] = useState<string | null>(null);
  const [previewTitle, setPreviewTitle] = useState("");
  const [previewHtml, setPreviewHtml] = useState<string | null>(null);
  const [previewErr, setPreviewErr] = useState<string | null>(null);

  const load = useCallback(async () => {
    try {
      setReports(await reportsApi.list());
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  const remove = async (r: Report) => {
    await reportsApi.remove(r.id);
    await load();
  };

  const openPreview = async (r: Report) => {
    setPreview(r.id);
    setPreviewTitle(r.title);
    setPreviewHtml(null);
    setPreviewErr(null);
    try {
      const html = await apiText(`/api/reports/${r.id}/html`);
      setPreviewHtml(html);
    } catch (e: any) {
      setPreviewErr(e.message || "Could not load report HTML");
    }
  };

  return (
    <div className="mx-auto max-w-5xl px-6 py-10">
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Reports</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Self-contained HTML and PDF reports generated by Borealis from your chats.
          </p>
        </div>
        <Button variant="secondary" size="sm" onClick={load}>
          Refresh
        </Button>
      </div>

      {loading ? (
        <div className="mt-8 space-y-3">
          {[0, 1, 2].map((i) => (
            <Skeleton key={i} className="h-24 w-full rounded-xl" />
          ))}
        </div>
      ) : reports.length === 0 ? (
        <Card className="mt-8 flex flex-col items-center gap-3 py-16 text-center">
          <FileText className="h-10 w-10 text-muted-foreground/40" />
          <p className="text-sm text-muted-foreground">
            No reports yet. Ask Borealis in a chat to "create a report" and it will land here as HTML + PDF.
          </p>
        </Card>
      ) : (
        <div className="mt-8 space-y-3">
          {reports.map((r) => (
            <Card key={r.id} className="flex items-center gap-4 p-4 transition-colors hover:border-foreground/20">
              <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-aurora-teal/20 to-aurora-violet/20 text-aurora-teal">
                <FileText className="h-5 w-5" />
              </div>
              <div className="min-w-0 flex-1">
                <div className="flex items-center gap-2">
                  <span className="truncate font-medium text-foreground">{r.title}</span>
                  <Badge variant="aurora">HTML + PDF</Badge>
                </div>
                <div className="mt-1 truncate text-xs text-muted-foreground">
                  {r.subtitle || "No subtitle"}
                </div>
                <div className="mt-1.5 flex flex-wrap items-center gap-3 text-xs text-muted-foreground">
                  <span>Created {formatDate(r.created_at)}</span>
                  {r.chat_id && (
                    <a
                      href={`#/chat/${r.chat_id}`}
                      className="inline-flex items-center gap-1 text-aurora-teal hover:underline"
                    >
                      <MessageSquare className="h-3 w-3" />
                      {r.chat_title || "source chat"}
                    </a>
                  )}
                </div>
              </div>
              <div className="flex shrink-0 items-center gap-1.5">
                <Button variant="outline" size="sm" onClick={() => openPreview(r)}>
                  <Eye className="h-4 w-4" /> Preview
                </Button>
                <Button
                  variant="ghost"
                  size="icon"
                  onClick={() => openProtected("pdf", `/api/reports/${r.id}/pdf`, `${r.title}.pdf`)}
                  title="Download PDF"
                  className="text-muted-foreground hover:text-aurora-teal"
                >
                  <Download className="h-4 w-4" />
                </Button>
                <Button variant="ghost" size="icon" onClick={() => remove(r)} title="Delete report" className="text-muted-foreground hover:text-destructive">
                  <Trash2 className="h-4 w-4" />
                </Button>
              </div>
            </Card>
          ))}
        </div>
      )}

      {/* report preview dialog */}
      <Dialog open={!!preview} onOpenChange={(o) => !o && setPreview(null)}>
        <DialogContent className="flex max-h-[85vh] max-w-4xl flex-col overflow-hidden p-0">
          <DialogHeader className="px-6 pt-5">
            <DialogTitle>{previewTitle}</DialogTitle>
            <DialogDescription>
              This export uses a fixed light, print-oriented document theme and renders identically to the PDF.
            </DialogDescription>
          </DialogHeader>
          <div className="min-h-0 flex-1 overflow-hidden px-6 pb-6">
            {previewHtml ? (
              <iframe srcDoc={previewHtml} className="h-[70vh] w-full rounded-xl border bg-white" sandbox="" title="Report preview" />
            ) : previewErr ? (
              <div className="flex h-[calc(70vh-2rem)] items-center justify-center rounded-xl border border-destructive/30 bg-destructive/10 text-sm text-destructive" role="alert">
                {previewErr}
              </div>
            ) : (
              <div className="space-y-3 p-2">
                <Skeleton className="h-6 w-1/2" />
                <Skeleton className="h-64 w-full" />
              </div>
            )}
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
