/**
 * Journey C — Revised work product (docs/END_TO_END_ACCEPTANCE.md).
 *
 * Real production build + real Chromium + the scripted provider; reuses the
 * journey-B finance flow (regenerated byte-identical CSV fixtures uploaded
 * through the real chat picker) and then turns the produced report into an
 * edited, rewritten, versioned, and exported document through the real
 * Documents workbench. Covers:
 *   - a real chat turn (query_data → render_chart → create_report) that
 *     persists a legacy report with the independently computed June numbers
 *     as its query table; the chat receipts (query result, chart card,
 *     report card) render in the real UI;
 *   - "Create editable copy" through the real ReportsView button → the copy's
 *     revision 1 deep-equals the stored legacy payload and is honestly
 *     unverified; the original report's HTML/PDF bytes are hash-verified
 *     unchanged across every later copy/edit/rewrite/publish step and the
 *     full backend restart;
 *   - a manual one-sentence correction with ZERO provider calls (asserted via
 *     the provider request counters), then a selected-passage rewrite driven
 *     by the scripted provider: inspect the diff, REJECT once, request again
 *     with a second scripted proposal, ACCEPT; unrelated sections, tables,
 *     and chart state stay byte-identical (stored-revision comparison +
 *     rendered workbench);
 *   - concurrency and CAS: a head move under an open UI draft surfaces the
 *     conflict dialog with the local draft preserved and the explicit
 *     reapply path lands a new revision; stale revision CAS saves are 409
 *     with current-head metadata; a stale proposal can never be accepted
 *     (409 + durable `stale`, inspectable-then-dismissible); a publish with a
 *     stale expected head is 409 `DOCUMENT_REVISION_CONFLICT` with
 *     current-head metadata (`DOCUMENT_HEAD_MOVED` is the completion-time
 *     recheck code) plus the UI recovery surface;
 *   - TWO published versions through the real publish button (immutable older
 *     exports hash-verified after the newer publish; v2 supersedes v1), one
 *     operation-UUID replay proves publication idempotency, and all four
 *     frozen-version exports are downloaded through real authenticated
 *     browser downloads: HTML self-contained (no external src/href, CSP,
 *     nosniff), PDF `%PDF-` magic + nontrivial bytes, the Markdown ZIP holds
 *     a real document.md + relative chart PNG assets + manifest.json with
 *     verified CRCs, and the DOCX is a readable OOXML zip whose
 *     word/document.xml carries the narrative and a native table;
 *   - rewrite bounds: the >8,000-char honest UI gate plus server 400
 *     OVERSIZE/INVALID (including a split surrogate pair), 409 selection-hash
 *     mismatch, and 409 one-active-rewrite;
 *   - foreign accounts get 404 on documents/publications/exports; a
 *     same-instance share recipient gets read-only detail with the payload
 *     omitted and is denied editable-copy;
 *   - closed dialogs keep their error/success slots (duplicate-template-name
 *     409 surfaces inside the dialog, closed dialog leaks nothing);
 *   - a full backend restart proves the durable document/revision/
 *     publication/rewrite history and frozen export bytes survive.
 *
 * Documented acceptance-harness capability gap (reported, not worked around):
 * the chat turn DOES render a chart (the chart card shows in chat), but a
 * scripted provider can never reference it inside the same turn's
 * `create_report` call: chart ids are server-minted run-scoped random UUIDs
 * and the fixture replays static step scripts (no tool-result echo), so the
 * 12-character model-garble fallback cannot match. The legacy report
 * therefore carries the query table + narrative with an EMPTY chart list,
 * and the chart-bearing document surfaces (chart PNGs in the Markdown ZIP /
 * DOCX, evidence appendix numbering, revision-bound charts) are exercised on
 * a second document created through the product's own first-party
 * explicit-tree creation contract (`POST /api/documents` `{tree}` — the same
 * service shape M16 composes) and published/exported through the real
 * workbench.
 *
 * Skipped sub-check with reason: "a legacy report with no stored payload".
 * Product code only ever creates reports through a completed agent turn, and
 * the normalized payload is dropped only when its serialization exceeds
 * 400,000 chars; with per-tool-call arguments bounded at 20,000 chars and the
 * provider script body bounded at 256 KiB, no scripted turn (and no
 * delete-payload API) can produce a payload-less report inside this harness.
 * The reachable honest boundary IS exercised: copies are owner-only (foreign
 * 404), and the recipient of a share never sees the payload nor may copy.
 *
 * Screenshots use the harness's content-free sequential names. Numeric
 * expectations come only from `fixtures/lib/finance-expected.mjs`.
 */
import { createHash, randomUUID } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { inflateRawSync } from "node:zlib";
import { HarnessError, assert, pollUntil } from "../harness/util.mjs";
import {
  COMMITTED_EXPECTED,
  expectedAnalysisRows,
  verifyCommittedExpected,
} from "../fixtures/lib/finance-expected.mjs";

export const JOURNEY_ID = "C";
export const IMPLEMENTED = true;

const EMAIL_A = "e2e-journey-c@borealis.test";
const EMAIL_B = "e2e-journey-c-foreign@borealis.test";
const PASSWORD = "borealis-e2e-journey-c-pass";

const ANSWER_REPORT = "FINAL-C-REPORT-4a17";
const REPORT_TITLE = "June 2025 personal-finance report (E2E-C)";
const CHART_TITLE = "June 2025 net by category (E2E-C)";
const DOC_T_TITLE = "Comparison memo (E2E-C)";

const SENT_ORIGINAL = "The report baseline sentence delta 2231 stands here.";
const SENT_EDITED = "The report baseline sentence epsilon 7788 stands here.";
const SENT_CONFLICT = "Method note gamma 3345 added in the UI during the race.";
const SENT_API_RACE = "Method note beta 8890 added by the first race writer.";
const SENT_V2 = "Breakdown note zeta 5566 added before the second publication.";
const REPL_1 = "Rewritten draft one 4412 keeps the citation and tightens the wording.";
const REPL_2 = "Rewritten draft two 9902 is concise and keeps the ledger citation.";
const REPL_3 = "Rewritten draft three 6602 must never be applied.";
const REWRITE_INSTRUCTION = "Tighten this sentence; keep the meaning and the ledger reference.";

const MEMO_V1 = "June memo sentence alpha 1147 cites [1] and keeps [9] unresolved.";
const MEMO_V2 = "June memo sentence omega 5561 cites [1][2] and keeps [9] unresolved.";

const PNG_MAGIC = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

/* ------------------------------------------------------------------ helpers */

async function goHash(session, route) {
  await session.page.evaluate((target) => {
    window.location.hash = target;
  }, route);
}

async function expectText(session, text, timeoutMs = 20_000) {
  await session.page.getByText(text).first().waitFor({ timeout: timeoutMs });
}

function toolStep(id, namePieces, argumentObject) {
  return {
    type: "tool_call",
    id,
    name_pieces: namePieces,
    argument_pieces: [JSON.stringify(argumentObject)],
  };
}

function textStep(pieces) {
  return { type: "text", pieces };
}

function sha256(buffer) {
  return createHash("sha256").update(buffer).digest("hex");
}

function sha256Text(text) {
  return sha256(Buffer.from(text, "utf8"));
}

/** Manual CRC32 (ZIP member integrity), independent of runtime version. */
const CRC_TABLE = (() => {
  const table = new Int32Array(256);
  for (let n = 0; n < 256; n += 1) {
    let c = n;
    for (let k = 0; k < 8; k += 1) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c;
  }
  return table;
})();

function crc32(buffer) {
  let crc = -1;
  for (let i = 0; i < buffer.length; i += 1) crc = (crc >>> 8) ^ CRC_TABLE[(crc ^ buffer[i]) & 0xff];
  return (crc ^ -1) >>> 0;
}

/**
 * Minimal strict ZIP central-directory reader: name → bytes, with CRC and
 * size verification per member (stored or deflate). Shared by the Markdown
 * ZIP and the DOCX/OOXML assertions; malformed archives fail loudly.
 */
function readZip(buffer, code) {
  let eocd = -1;
  const floor = Math.max(0, buffer.length - 66_000);
  for (let i = buffer.length - 22; i >= floor; i -= 1) {
    if (buffer.readUInt32LE(i) === 0x06054b50) {
      eocd = i;
      break;
    }
  }
  assert(eocd >= 0, `${code}_ZIP_EOCD_MISSING`);
  const count = buffer.readUInt16LE(eocd + 10);
  assert(count > 0 && count < 512, `${code}_ZIP_MEMBER_COUNT`, String(count));
  const members = new Map();
  let p = buffer.readUInt32LE(eocd + 16);
  for (let n = 0; n < count; n += 1) {
    assert(buffer.readUInt32LE(p) === 0x02014b50, `${code}_ZIP_CENTRAL_MALFORMED`);
    const method = buffer.readUInt16LE(p + 10);
    const crc = buffer.readUInt32LE(p + 16);
    const csize = buffer.readUInt32LE(p + 20);
    const usize = buffer.readUInt32LE(p + 24);
    const nameLen = buffer.readUInt16LE(p + 28);
    const extraLen = buffer.readUInt16LE(p + 30);
    const commentLen = buffer.readUInt16LE(p + 32);
    const localOff = buffer.readUInt32LE(p + 42);
    const name = buffer.toString("utf8", p + 46, p + 46 + nameLen);
    assert(buffer.readUInt32LE(localOff) === 0x04034b50, `${code}_ZIP_LOCAL_MALFORMED`, name);
    const localNameLen = buffer.readUInt16LE(localOff + 26);
    const localExtraLen = buffer.readUInt16LE(localOff + 28);
    const dataStart = localOff + 30 + localNameLen + localExtraLen;
    const raw = buffer.subarray(dataStart, dataStart + csize);
    let data;
    if (method === 0) data = Buffer.from(raw);
    else if (method === 8) data = Buffer.from(inflateRawSync(raw));
    else throw new HarnessError(`${code}_ZIP_METHOD_UNSUPPORTED`, `${name}:${method}`);
    assert(data.length === usize, `${code}_ZIP_SIZE_MISMATCH`, name);
    assert(crc32(data) === (crc >>> 0), `${code}_ZIP_CRC_MISMATCH`, name);
    members.set(name, data);
    p += 46 + nameLen + extraLen + commentLen;
  }
  return members;
}

/** Authenticated raw-byte fetch inside the page context (exports, artifacts). */
async function fetchBytes(session, route, expectStatus = 200, code = "BYTES_FETCH") {
  const token = await session.token();
  const result = await session.page.evaluate(
    async ({ route, token }) => {
      const res = await fetch(route, { headers: { Authorization: `Bearer ${token}` } });
      const bytes = new Uint8Array(await res.arrayBuffer());
      let binary = "";
      const CHUNK = 8192;
      for (let i = 0; i < bytes.length; i += CHUNK) {
        binary += String.fromCharCode(...bytes.subarray(i, i + CHUNK));
      }
      return {
        status: res.status,
        contentType: res.headers.get("content-type") || "",
        disposition: res.headers.get("content-disposition") || "",
        csp: res.headers.get("content-security-policy") || "",
        nosniff: res.headers.get("x-content-type-options") || "",
        b64: btoa(binary),
      };
    },
    { route, token }
  );
  assert(result.status === expectStatus, `${code}_STATUS`, `${route} → ${result.status}`);
  return { ...result, buffer: Buffer.from(result.b64, "base64") };
}

/** Click that triggers a real authenticated browser download, saved in-tree. */
async function downloadVia(session, click, destinationPath) {
  const [download] = await Promise.all([
    session.page.waitForEvent("download", { timeout: 120_000 }),
    click(),
  ]);
  const suggested = download.suggestedFilename();
  await download.saveAs(destinationPath);
  return { name: suggested, buffer: await fs.promises.readFile(destinationPath) };
}

/**
 * Real keyboard selection of the last `chars` characters of the textarea's
 * (single logical-line) content. Keyboard-driven selection is what fires the
 * rewrite panel's React `onSelect` mirror (a programmatically dispatched
 * `select` event does not — proven against the built UI).
 */
async function selectTailViaKeyboard(session, locator, chars) {
  await locator.click();
  await session.page.keyboard.press("End");
  await session.page.keyboard.down("Shift");
  for (let i = 0; i < chars; i += 1) await session.page.keyboard.press("ArrowLeft");
  await session.page.keyboard.up("Shift");
}


/** No external `src`/`href` targets (data:/anchor targets are allowed). */
function assertSelfContainedHtml(html, code) {
  const offenders = [...html.matchAll(/(?:src|href)=["']([^"']*)["']/gi)]
    .map((match) => match[1])
    .filter((url) => url.length > 0 && !/^(?:data:|#)/i.test(url));
  assert(offenders.length === 0, `${code}_HTML_EXTERNAL_REF`, offenders[0]?.slice(0, 60));
}

/**
 * The publication HTML is built with `static: true`: no chart runtime script
 * and no URL literals anywhere in the document (the legacy dynamic report
 * HTML inlines the chart library, so only the src/href scan applies there).
 */
function assertStaticPublicationHtml(html, code) {
  assertSelfContainedHtml(html, code);
  assert(!/https?:\/\//i.test(html), `${code}_HTML_SCHEME_LITERAL`);
}

function assertPdf(buffer, code) {
  assert(buffer.length > 4_096, `${code}_PDF_TOO_SMALL`, String(buffer.length));
  assert(buffer.subarray(0, 5).toString("latin1") === "%PDF-", `${code}_PDF_MAGIC`);
  assert(buffer.subarray(-1024).toString("latin1").includes("%%EOF"), `${code}_PDF_EOF`);
}

async function revisionPayload(session, documentId, revisionId) {
  const res = await session.apiFetch(`/api/documents/${documentId}/revisions/${revisionId}`, { expectStatus: 200 });
  return res.body.payload;
}

async function waitHead(session, documentId, wantedRevision, code) {
  const detail = await pollUntil(
    async () => {
      const res = await session.apiFetch(`/api/documents/${documentId}`, { expectStatus: 200 });
      return res.body?.current_revision === wantedRevision ? res.body : null;
    },
    { deadlineMs: 25_000, intervalMs: 200 }
  );
  assert(detail !== null, code, `head did not reach revision ${wantedRevision}`);
  return detail;
}

/** Newest-first rewrite poller; `excludeId` skips an already-applied row. */
async function waitCompletedRewrite(session, documentId, excludeId, replacement, code) {
  const found = await pollUntil(
    async () => {
      const res = await session.apiFetch(`/api/documents/${documentId}/rewrites`, { expectStatus: 200 });
      const items = res.body?.items ?? [];
      return items.find((item) => item.status === "completed" && item.id !== excludeId) ?? null;
    },
    { deadlineMs: 40_000, intervalMs: 250 }
  );
  assert(found !== null, `${code}_NOT_COMPLETED`);
  assert(found.replacement === replacement, `${code}_PROPOSAL`);
  return found;
}

function publicationsRow(session, position) {
  // Publications render newest-first; position 0 is the newest version.
  return session.page.locator('section[aria-labelledby="publication-history-heading"] ol > li').nth(position);
}

/* ------------------------------------------------------------------ journey */

export async function run(ctx) {
  const { server, provider, browser, workspace, artifactsDir, repoRoot } = ctx;
  const artifacts = [];
  const checks = {};
  const exportsDir = workspace.assertOwnedPath(path.join(artifactsDir, "exports"));
  fs.mkdirSync(exportsDir, { recursive: true, mode: 0o700 });

  /* -- P0: regenerate the finance fixtures INTO THE RUN WORKSPACE ----------- */
  const inputsDir = workspace.assertOwnedPath(path.join(workspace.root, "inputs"));
  await fs.promises.mkdir(inputsDir, { recursive: true, mode: 0o700 });
  const sampleDir = path.join(inputsDir, "sample");
  const generator = spawnSync("pnpm", ["--filter", "borealis-server", "exec", "tsx", "../data/generate_sample.ts"], {
    cwd: path.join(repoRoot, "server"),
    env: { ...process.env, E2E_SAMPLE_DIR: sampleDir },
    encoding: "utf8",
    timeout: 120_000,
  });
  assert(generator.status === 0, "GENERATOR_FAILED", String(generator.status));
  const fixtureNames = ["accounts.csv", "transactions.csv", "budget.csv", "networth.csv"];
  for (const name of fixtureNames) {
    const generated = await fs.promises.readFile(path.join(sampleDir, name));
    const committed = await fs.promises.readFile(path.join(repoRoot, "data", "sample", name));
    assert(generated.equals(committed), "GENERATOR_BYTES_DIFFER", name);
  }
  const transactionsText = await fs.promises.readFile(path.join(sampleDir, "transactions.csv"), "utf8");
  const helperMismatches = verifyCommittedExpected(transactionsText);
  assert(helperMismatches.length === 0, "EXPECTED_VALUES_DRIFT", helperMismatches.join(" | "));
  const expectedJune = expectedAnalysisRows(transactionsText, "2025-06");
  assert(expectedJune.length === COMMITTED_EXPECTED.june_keys, "EXPECTED_JUNE_ROWS");
  // June rows are ordered by (month, category): the report table + chart use
  // [category, tx_count, net_amount] straight from the independent helper.
  const juneTable = expectedJune.map((row) => [row[1], row[2], row[3]]);
  const juneCategories = juneTable.map((row) => String(row[0]));
  const juneNets = juneTable.map((row) => row[2]);
  const netText = (value) => String(value);
  checks.fixture_june_keys = expectedJune.length;

  const chartSpec = {
    type: "bar",
    title: CHART_TITLE,
    categories: juneCategories,
    series: [{ name: "net_amount", data: juneNets }],
    x_label: "category",
    y_label: "net",
  };

  /* -- P1: account + the four uploads through the real chat picker ---------- */
  const session = await browser.newSession({ origin: server.origin });
  let sessionForeign = null;
  try {
    await session.register({ email: EMAIL_A, password: PASSWORD });
    artifacts.push(await session.screenshot(artifactsDir));

    const fileInput = () => session.page.locator('input[aria-label="Upload a source file"]');
    const picker = () => session.page.locator('button[aria-label^="Chat sources:"]');
    await picker().click();
    for (const name of fixtureNames) {
      await fileInput().setInputFiles(path.join(sampleDir, name));
      await pollUntil(
        async () => {
          const res = await session.apiFetch("/api/sources", { expectStatus: 200 });
          return (res.body?.items ?? []).length === fixtureNames.indexOf(name) + 1;
        },
        { deadlineMs: 30_000, intervalMs: 200 }
      );
    }
    const byName = await pollUntil(
      async () => {
        const res = await session.apiFetch("/api/sources", { expectStatus: 200 });
        const items = res.body?.items ?? [];
        if (items.length !== 4) return null;
        if (!items.every((item) => item.status === "ready")) return null;
        const map = {};
        for (const item of items) map[item.display_name] = item;
        return Object.keys(map).length === 4 ? map : null;
      },
      { deadlineMs: 90_000, intervalMs: 300 }
    );
    assert(byName !== null, "SOURCES_NOT_READY");
    await expectText(session, "4 sources");
    await picker().click().catch(() => undefined);
    await session.page.keyboard.press("Escape");

    /* -- P2: scripted turn → legacy report with the June query table -------- */
    //
    // The turn renders a real chart (the chart card shows in the chat), but
    // the scripted `create_report` step CANNOT reference it: chart ids are
    // server-minted run-scoped random UUIDs and the provider fixture replays
    // static steps with no tool-result echo, so the 12-char garble fallback
    // has nothing to match. The chart reference therefore stays empty in the
    // legacy payload (documented gap in the header + the final report); the
    // chart-bearing document contract is exercised on the first-party
    // tree-created document in P9.
    const juneSql =
      "SELECT category, COUNT(*) AS transactions, ROUND(SUM(amount), 2) AS net_amount " +
      "FROM transactions WHERE LEFT(CAST(date AS VARCHAR), 7) = '2025-06' GROUP BY 1 ORDER BY 1";
    const overviewBase =
      `June closed with ${expectedJune.length} category groups in the ledger. ` +
      `Net groceries came to ${netText(COMMITTED_EXPECTED.june_groceries_net)} across ` +
      `${COMMITTED_EXPECTED.june_groceries_tx_count} transactions. ${SENT_ORIGINAL}`;
    const reportArgs = {
      title: REPORT_TITLE,
      subtitle: "Scripted finance turn (E2E-C)",
      sections: [
        { heading: "Overview", markdown: overviewBase },
        { heading: "Breakdown", markdown: "Category totals for June 2025 appear in the table below." },
        { heading: "Method", markdown: "All values come from the attached June ledger." },
      ],
      tables: [{ columns: ["category", "transactions", "net_amount"], rows: juneTable }],
    };
    const beforeReport = await provider.state();
    await provider.setScript({
      steps: [
        toolStep("call_c_query", ["query", "_data"], { sql: juneSql }),
        toolStep("call_c_chart", ["render", "_chart"], { spec: chartSpec }),
        toolStep("call_c_report", ["create", "_report"], reportArgs),
        textStep(["June analysis complete; the report is ready. ", ANSWER_REPORT]),
      ],
      onExhausted: "fail",
    });
    await session.page.getByLabel("Ask Borealis about your data").fill("Give me a June 2025 report with the category table.");
    await session.page.getByRole("button", { name: "Send message", exact: true }).click();
    await expectText(session, ANSWER_REPORT, 180_000);
    await expectText(session, "Query result 1");
    await session.page.getByRole("button", { name: `Expand chart: ${CHART_TITLE}` }).waitFor({ timeout: 60_000 });
    await expectText(session, "Generated by Borealis · HTML + PDF", 30_000);
    artifacts.push(await session.screenshot(artifactsDir));

    // 4 scripted steps + the chat-title probe; poll a bounded deadline so the
    // late title POST is counted exactly.
    const reportArity = await pollUntil(
      async () => (await provider.state()).chat_calls >= beforeReport.chat_calls + 5,
      { deadlineMs: 20_000, intervalMs: 250 }
    );
    assert(reportArity === true, "REPORT_TURN_PROVIDER_ARITY_WAIT");
    const afterReport = await provider.state();
    assert(
      afterReport.chat_calls - beforeReport.chat_calls === 5 && afterReport.embedding_calls === beforeReport.embedding_calls,
      "REPORT_TURN_ARITY",
      `chat=+${afterReport.chat_calls - beforeReport.chat_calls}`
    );
    checks.report_turn_chat_calls = afterReport.chat_calls - beforeReport.chat_calls;

    const chatList = (await session.apiFetch("/api/chats", { expectStatus: 200 })).body?.items ?? [];
    assert(chatList.length === 1, "CHAT_COUNT", String(chatList.length));
    const chatId = chatList[0].id;
    const chatDetail = (await session.apiFetch(`/api/chats/${chatId}`, { expectStatus: 200 })).body;
    assert(chatDetail.source_mode === "selected" && (chatDetail.sources ?? []).length === 4, "CHAT_SCOPE");
    const assistant = (chatDetail.messages ?? []).find((m) => m.role === "assistant" && m.meta?.report);
    assert(assistant !== undefined, "REPORT_NOT_PERSISTED");
    const reportId = assistant.meta.report;
    assert(Array.isArray(assistant.meta.charts) && assistant.meta.charts.length === 1, "CHAT_CHART_PERSISTED");
    const receipt = assistant.meta.query_results?.[0];
    assert(receipt !== undefined && receipt.truncated === false, "QUERY_RECEIPT");
    assert(receipt.row_count === juneTable.length, "RECEIPT_ROWS", String(receipt.row_count));
    for (let i = 0; i < juneTable.length; i += 1) {
      const [aCat, aCount, aNet] = receipt.rows[i];
      const [eCat, eCount, eNet] = juneTable[i];
      assert(String(aCat) === String(eCat) && Number(aCount) === eCount, "RECEIPT_ROW_MATCH", String(i));
      assert(
        Math.abs(Math.round(Number(aNet) * 100) - Math.round(Number(eNet) * 100)) <= 1,
        "RECEIPT_NET_TOLERANCE",
        String(i)
      );
    }
    const chatMetaSnapshot = JSON.stringify(assistant.meta);

    const reportRow = await pollUntil(
      async () => {
        const res = await session.apiFetch("/api/reports", { expectStatus: 200 });
        const items = res.body?.items ?? [];
        return items.length === 1 && items[0].has_html && items[0].has_pdf ? items[0] : null;
      },
      { deadlineMs: 30_000, intervalMs: 250 }
    );
    assert(reportRow !== null, "REPORT_LIST_NOT_READY");
    assert(reportRow.id === reportId && reportRow.version === 1 && reportRow.supersedes === null, "REPORT_LINEAGE");
    const reportDetail = (await session.apiFetch(`/api/reports/${reportId}`, { expectStatus: 200 })).body;
    assert(typeof reportDetail.payload === "object" && reportDetail.payload !== null, "REPORT_PAYLOAD_STORED");
    const reportPayload = reportDetail.payload;
    assert(reportPayload.sections.length === 3 && reportPayload.charts.length === 0, "REPORT_PAYLOAD_SHAPE");
    assert(
      JSON.stringify(reportPayload.tables[0].rows) === JSON.stringify(juneTable),
      "REPORT_TABLE_VALUES",
      "report table drifted from the independently computed fixture values"
    );
    checks.report = { id: reportId.slice(0, 8), version: 1, table_rows: juneTable.length };

    /* -- P3: legacy baseline bytes (hash-verified unchanged later) ---------- */
    const legacyHtml = await fetchBytes(session, `/api/reports/${reportId}/html`, 200, "LEGACY");
    const legacyPdf = await fetchBytes(session, `/api/reports/${reportId}/pdf`, 200, "LEGACY");
    assertSelfContainedHtml(legacyHtml.buffer.toString("utf8"), "LEGACY");
    assertPdf(legacyPdf.buffer, "LEGACY");
    const legacyHashes = {
      html: sha256(legacyHtml.buffer),
      pdf: sha256(legacyPdf.buffer),
      payload: sha256(Buffer.from(JSON.stringify(reportPayload), "utf8")),
    };
    checks.legacy_bytes = { html: legacyHashes.html.slice(0, 12), pdf: legacyHashes.pdf.slice(0, 12) };

    /* -- P4: create the editable copy through the real ReportsView ---------- */
    await goHash(session, "/reports");
    await expectText(session, REPORT_TITLE);
    await session.page.getByRole("button", { name: "Copy", exact: true }).click();
    await pollUntil(
      async () => (await session.page.evaluate(() => window.location.hash))?.startsWith("#/documents/"),
      { deadlineMs: 20_000, intervalMs: 150 }
    ).then((moved) => assert(moved === true, "COPY_DID_NOT_NAVIGATE"));
    const docR = (await session.page.evaluate(() => window.location.hash)).split("/").pop();
    await expectText(session, "Revision 1");
    await expectText(session, "unverified / manual", 15_000);
    await expectText(session, "This revision carries no evidence references");
    artifacts.push(await session.screenshot(artifactsDir));

    const docRDetail = (await session.apiFetch(`/api/documents/${docR}`, { expectStatus: 200 })).body;
    const docRRev1Id = docRDetail.current_revision_id;
    assert(docRDetail.origin.report_id === reportId, "COPY_ORIGIN_REPORT");
    assert(docRDetail.current_revision === 1 && docRDetail.latest_publication_version === null, "COPY_HEAD");
    assert(docRDetail.title === REPORT_TITLE, "COPY_TITLE");
    const rev1 = await revisionPayload(session, docR, docRRev1Id);
    assert(rev1.verified === false && rev1.evidence.length === 0 && rev1.charts.length === 0, "COPY_UNVERIFIED");
    assert(
      JSON.stringify(rev1.sections.map((s) => [s.heading, s.markdown])) ===
        JSON.stringify(reportPayload.sections.map((s) => [s.heading, s.markdown])),
      "COPY_SECTIONS_MATCH_PAYLOAD"
    );
    assert(
      JSON.stringify(rev1.tables[0].rows) === JSON.stringify(reportPayload.tables[0].rows),
      "COPY_TABLE_MATCHES_PAYLOAD"
    );
    await goHash(session, "/documents");
    await expectText(session, "report copy", 15_000);
    artifacts.push(await session.screenshot(artifactsDir));
    checks.copy = { document: docR.slice(0, 8) };

    /* -- P5: one manual sentence correction, ZERO provider calls ------------ */
    await goHash(session, `/documents/${docR}`);
    await expectText(session, "Revision 1");
    const sectionOne = () => session.page.getByLabel("Markdown of section 1");
    const overviewHead = await sectionOne().inputValue();
    assert(overviewHead.endsWith(SENT_ORIGINAL), "SENTENCE_NOT_AT_TAIL");
    await selectTailViaKeyboard(session, sectionOne(), SENT_ORIGINAL.length);
    await session.page.keyboard.type(SENT_EDITED, { delay: 4 });
    await expectText(session, "Unsaved changes", 10_000);
    const providerBeforeManual = await provider.state();
    await session.page.getByRole("button", { name: "Save revision", exact: true }).click();
    const head2 = await waitHead(session, docR, 2, "MANUAL_HEAD");
    const providerAfterManual = await provider.state();
    assert(
      providerAfterManual.chat_calls === providerBeforeManual.chat_calls &&
        providerAfterManual.embedding_calls === providerBeforeManual.embedding_calls,
      "MANUAL_EDIT_ISSUED_MODEL_CALL",
      "a manual narrative edit must never touch the provider"
    );
    checks.manual_edit_provider_calls = 0;

    const rev2 = await revisionPayload(session, docR, head2.current_revision_id);
    assert(
      rev2.sections[0].markdown === overviewHead.replace(SENT_ORIGINAL, SENT_EDITED),
      "MANUAL_EDIT_MISPLACED",
      "the keyboard selection did not replace exactly the original sentence"
    );
    const rev1Again = await revisionPayload(session, docR, docRRev1Id);
    assert(
      rev1Again.sections[0].markdown.includes(SENT_ORIGINAL) && !rev1Again.sections[0].markdown.includes(SENT_EDITED),
      "REV1_MUTATED"
    );
    assert(rev2.sections[0].markdown.includes(SENT_EDITED), "REV2_NOT_EDITED");
    assert(
      JSON.stringify(rev2.sections.slice(1)) === JSON.stringify(rev1.sections.slice(1)),
      "MANUAL_EDIT_TOUCHED_OTHER_SECTIONS"
    );
    assert(JSON.stringify(rev2.tables) === JSON.stringify(rev1.tables), "MANUAL_EDIT_TOUCHED_TABLE");

    // Reload mid-edit: the workbench's durable draft IS the saved revision.
    // (The editor intentionally keeps no unsaved-text client persistence —
    // explicit saves with base-revision CAS are the product's design; the
    // conflict surface below covers the racing-writer case.)
    await session.page.reload({ waitUntil: "domcontentloaded" });
    await expectText(session, "Revision 2", 30_000);
    await session.page.waitForFunction(
      () => !document.body.innerText.includes("Unsaved changes"),
      null,
      { timeout: 15_000 }
    );
    assert(!(await session.page.getByText("Unsaved changes").isVisible().catch(() => false)), "STALE_DIRTY_AFTER_RELOAD");
    assert(!(await session.page.locator('[role="alert"]').first().isVisible().catch(() => false)), "STALE_ALERT_AFTER_RELOAD");
    assert((await sectionOne().inputValue()).includes(SENT_EDITED), "RELOAD_LOST_SAVED_DRAFT");
    artifacts.push(await session.screenshot(artifactsDir));

    // Legacy artifacts are still byte-identical after copy + manual edit.
    const legacyHtml2 = await fetchBytes(session, `/api/reports/${reportId}/html`, 200, "LEGACY");
    const legacyPdf2 = await fetchBytes(session, `/api/reports/${reportId}/pdf`, 200, "LEGACY");
    assert(sha256(legacyHtml2.buffer) === legacyHashes.html, "LEGACY_HTML_CHANGED");
    assert(sha256(legacyPdf2.buffer) === legacyHashes.pdf, "LEGACY_PDF_CHANGED");
    const reportAfterEdit = (await session.apiFetch(`/api/reports/${reportId}`, { expectStatus: 200 })).body;
    assert(
      reportAfterEdit.version === 1 && JSON.stringify(reportAfterEdit.payload) === JSON.stringify(reportPayload),
      "LEGACY_PAYLOAD_CHANGED"
    );

    /* -- P6: selected-passage rewrite: reject once, then accept ------------- */
    session.allowStatuses([409, 404]);
    const overviewNow = await sectionOne().inputValue();
    assert(overviewNow.endsWith(SENT_EDITED), "REWRITE_TARGET_NOT_AT_TAIL");

    await provider.setScript({ steps: [{ type: "slow", delay_ms: 6000, pieces: [REPL_1] }], onExhausted: "fail" });
    const beforeRewrite1 = await provider.state();
    await session.page.getByRole("button", { name: "Request rewrite" }).waitFor({ timeout: 10_000 });
    await selectTailViaKeyboard(session, sectionOne(), SENT_EDITED.length);
    await expectText(session, `${SENT_EDITED.length} selected characters`, 10_000);
    await session.page.getByLabel("Rewrite instruction").fill(REWRITE_INSTRUCTION);
    await session.page.getByRole("button", { name: "Request rewrite", exact: true }).click();
    const rw1 = await pollUntil(
      async () => {
        const res = await session.apiFetch(`/api/documents/${docR}/rewrites`, { expectStatus: 200 });
        const items = res.body?.items ?? [];
        return items.length === 1 ? items[0] : null;
      },
      { deadlineMs: 20_000, intervalMs: 200 }
    );
    assert(rw1 !== null, "REWRITE_NOT_QUEUED");
    // One active rewrite per document: a second request while running is 409
    // (with a matching selection hash so the durable active guard, not the
    // selection check, is what rejects it).
    const busyRes = await session.apiFetch(`/api/documents/${docR}/rewrites`, {
      method: "POST",
      body: {
        base_revision_id: head2.current_revision_id,
        section_id: rev2.sections[1].id,
        selection_sha256: sha256Text(rev2.sections[1].markdown),
        instruction: "second request while one is active",
      },
    });
    assert(busyRes.status === 409 && busyRes.body?.code === "DOCUMENT_REWRITE_ACTIVE", "REWRITE_ACTIVE_409", String(busyRes.status));
    await expectText(session, "one rewrite at a time", 10_000);
    const rewrite1 = await waitCompletedRewrite(session, docR, null, REPL_1, "REWRITE_1");
    const afterRewrite1 = await provider.state();
    assert(afterRewrite1.chat_calls - beforeRewrite1.chat_calls === 1, "REWRITE_1_PROVIDER_ARITY");
    assert(rewrite1.status === "completed", "REWRITE_1_STATUS");

    // Inspect the diff in the real card, then REJECT (dismiss) once.
    //
    // REPORTED PRODUCT DEFECT (no workaround, no product edit — documented
    // in the run report): the RewritePanel's active-operation poll chain never
    // re-arms — `poll()` captures `listRequestRef.current` and then calls
    // `loadProposals()`, which INCREMENTS that same ref, so the guard
    // `listRequestRef.current !== requestId` always short-circuits the
    // reschedule (web/src/pages/DocumentWorkbench.tsx, poll()). A running
    // proposal therefore sits on the "rewriting…" badge until the page is
    // reloaded. Durable server truth (API-pollable) is asserted first, and
    // the real UI recovery action — reload — is then exercised.
    await session.page.reload({ waitUntil: "domcontentloaded" });
    await expectText(session, "Revision 2", 30_000);
    const card1 = session.page.locator(`[data-rewrite-id="${rw1.id}"]`);
    await card1.waitFor({ timeout: 20_000 });
    await card1.getByText("Current selection").waitFor({ timeout: 10_000 });
    await card1.getByText("Proposed replacement").waitFor({ timeout: 10_000 });
    assert((await card1.innerText()).includes(SENT_EDITED) && (await card1.innerText()).includes(REPL_1), "REWRITE_1_DIFF");
    artifacts.push(await session.screenshot(artifactsDir));
    await card1.getByRole("button", { name: "Reject", exact: true }).click();
    await pollUntil(
      async () => (await card1.count()) === 0,
      { deadlineMs: 15_000, intervalMs: 150 }
    ).then((gone) => assert(gone === true, "REJECT_LEFT_CARD"));
    const rejectedGet = await session.apiFetch(`/api/documents/${docR}/rewrites/${rw1.id}`);
    assert(rejectedGet.status === 404 && rejectedGet.body?.code === "DOCUMENT_REWRITE_NOT_FOUND", "REJECTED_REWRITE_404");
    const headAfterReject = (await session.apiFetch(`/api/documents/${docR}`, { expectStatus: 200 })).body;
    assert(headAfterReject.current_revision === 2, "REJECT_CREATED_REVISION");

    // Request again with the second scripted proposal, inspect, then ACCEPT.
    await provider.setScript({ steps: [textStep([REPL_2])], onExhausted: "fail" });
    const beforeRewrite2 = await provider.state();
    await selectTailViaKeyboard(session, sectionOne(), SENT_EDITED.length);
    await expectText(session, `${SENT_EDITED.length} selected characters`, 10_000);
    await session.page.getByLabel("Rewrite instruction").fill(REWRITE_INSTRUCTION);
    await session.page.getByRole("button", { name: "Request rewrite", exact: true }).click();
    const rw2 = await waitCompletedRewrite(session, docR, null, REPL_2, "REWRITE_2");
    const afterRewrite2 = await provider.state();
    assert(afterRewrite2.chat_calls - beforeRewrite2.chat_calls === 1, "REWRITE_2_PROVIDER_ARITY");
    // Same reload recovery as above (product defect): durable completion is
    // API-asserted, then the reloaded workbench surfaces the inspectable card.
    await session.page.reload({ waitUntil: "domcontentloaded" });
    await expectText(session, "Revision 2", 30_000);
    const card2 = session.page.locator(`[data-rewrite-id="${rw2.id}"]`);
    await card2.waitFor({ timeout: 20_000 });
    assert((await card2.innerText()).includes(SENT_EDITED) && (await card2.innerText()).includes(REPL_2), "REWRITE_2_DIFF");
    artifacts.push(await session.screenshot(artifactsDir));
    await card2.getByRole("button", { name: "Accept", exact: true }).click();
    await expectText(session, "Applied — the document now has a new model-authored revision", 20_000);
    const head3 = await waitHead(session, docR, 3, "ACCEPT_HEAD");
    const rev3 = await revisionPayload(session, docR, head3.current_revision_id);
    const accepted = await session.apiFetch(`/api/documents/${docR}/rewrites/${rw2.id}`, { expectStatus: 200 });
    assert(
      accepted.body.applied_revision_id === head3.current_revision_id && accepted.body.status === "completed",
      "REWRITE_APPLIED_LINK"
    );
    assert(
      rev3.sections[0].markdown === overviewNow.replace(SENT_EDITED, REPL_2),
      "REWRITE_APPLY_MISPLACED",
      "the accepted replacement did not land exactly on the selected passage"
    );
    assert(
      JSON.stringify(rev3.sections.slice(1)) === JSON.stringify(rev2.sections.slice(1)),
      "REWRITE_TOUCHED_OTHER_SECTIONS"
    );
    assert(JSON.stringify(rev3.tables) === JSON.stringify(rev2.tables), "REWRITE_TOUCHED_TABLE");
    const rev3History = (await session.apiFetch(`/api/documents/${docR}/revisions`, { expectStatus: 200 })).body?.items ?? [];
    assert(
      rev3History.find((entry) => entry.id === head3.current_revision_id)?.author_kind === "model" &&
        rev3History.filter((entry) => entry.author_kind === "model").length === 1,
      "REWRITE_AUTHOR_KIND"
    );
    assert((await sectionOne().inputValue()).includes(REPL_2), "WORKBENCH_NOT_UPDATED");

    /* -- P6b: a proposal cannot overwrite a newer head ---------------------- */
    await provider.setScript({ steps: [textStep([REPL_3])], onExhausted: "fail" });
    const overview3 = await sectionOne().inputValue();
    assert(overview3.endsWith(REPL_2), "REPL_2_NOT_AT_TAIL");
    await selectTailViaKeyboard(session, sectionOne(), REPL_2.length);
    await expectText(session, `${REPL_2.length} selected characters`, 10_000);
    await session.page.getByLabel("Rewrite instruction").fill("Another tightening pass against revision 3.");
    await session.page.getByRole("button", { name: "Request rewrite", exact: true }).click();
    const rw3 = await waitCompletedRewrite(session, docR, rw2.id, REPL_3, "REWRITE_3");
    // Move the head under the proposal with an unrelated-section edit.
    const raceAppend = await session.apiFetch(`/api/documents/${docR}/revisions`, {
      method: "POST",
      body: {
        base_revision_id: head3.current_revision_id,
        tree: {
          title: docRDetail.title,
          subtitle: rev3.subtitle,
          verified: rev3.verified,
          sections: [
            rev3.sections[0],
            rev3.sections[1],
            { id: rev3.sections[2].id, heading: rev3.sections[2].heading, markdown: `${rev3.sections[2].markdown} ${SENT_API_RACE}` },
          ],
          charts: rev3.charts,
          tables: rev3.tables,
          evidence: rev3.evidence,
        },
      },
      expectStatus: 201,
    });
    assert(raceAppend.body.document.current_revision === 4, "RACE_HEAD_APPEND");
    const staleAccept = await session.apiFetch(`/api/documents/${docR}/rewrites/${rw3.id}/accept`, {
      method: "POST",
      body: {},
    });
    assert(staleAccept.status === 409 && staleAccept.body?.code === "DOCUMENT_REWRITE_STALE", "STALE_ACCEPT_409", String(staleAccept.status));
    assert(staleAccept.body?.current_head?.revision === 4, "STALE_ACCEPT_HEAD_META");
    const staleRow = await session.apiFetch(`/api/documents/${docR}/rewrites/${rw3.id}`, { expectStatus: 200 });
    assert(staleRow.body.status === "stale" && staleRow.body.applied_revision_id === null, "STALE_NOT_MARKED");
    const headAfterStale = (await session.apiFetch(`/api/documents/${docR}`, { expectStatus: 200 })).body;
    assert(headAfterStale.current_revision === 4, "STALE_ACCEPT_APPLIED");
    // The stale proposal stays inspectable in the UI until dismissed.
    await session.page.reload({ waitUntil: "domcontentloaded" });
    await expectText(session, "Revision 4", 30_000);
    const staleCard = session.page.locator(`[data-rewrite-id="${rw3.id}"]`);
    await staleCard.waitFor({ timeout: 20_000 });
    assert((await staleCard.innerText()).includes("stale"), "STALE_CARD_BADGE");
    await staleCard.getByRole("button", { name: "Inspect proposal" }).click();
    assert((await staleCard.innerText()).includes(REPL_3), "STALE_PROPOSAL_NOT_INSPECTABLE");
    await staleCard.getByRole("button", { name: "Dismiss" }).click();
    await pollUntil(
      async () => (await staleCard.count()) === 0,
      { deadlineMs: 15_000, intervalMs: 150 }
    ).then((gone) => assert(gone === true, "STALE_DISMISS_FAILED"));
    checks.rewrite = { proposals: 3, rejected: 1, accepted: 1, stale_blocked: 1 };

    /* -- P7: head moved under an open draft: conflict + reapply ------------- */
    await expectText(session, "Revision 4");
    const sectionThree = () => session.page.getByLabel("Markdown of section 3");
    await sectionThree().click();
    await session.page.keyboard.press("End");
    await session.page.keyboard.type(` ${SENT_CONFLICT}`, { delay: 4 });
    await expectText(session, "Unsaved changes", 10_000);
    // A second writer appends through the API while the UI draft is pending.
    const head4 = (await session.apiFetch(`/api/documents/${docR}`, { expectStatus: 200 })).body;
    const rev4 = await revisionPayload(session, docR, head4.current_revision_id);
    await session.apiFetch(`/api/documents/${docR}/revisions`, {
      method: "POST",
      body: {
        base_revision_id: head4.current_revision_id,
        tree: {
          title: docRDetail.title,
          subtitle: rev4.subtitle,
          verified: rev4.verified,
          sections: [
            rev4.sections[0],
            rev4.sections[1],
            { ...rev4.sections[2], markdown: `${rev4.sections[2].markdown} SECOND-WRITER SENTINEL` },
          ],
          charts: rev4.charts,
          tables: rev4.tables,
          evidence: rev4.evidence,
        },
      },
      expectStatus: 201,
    });
    await session.page.getByRole("button", { name: "Save revision", exact: true }).click();
    const conflictDialog = session.page.getByRole("dialog", { name: "Revision conflict" });
    await conflictDialog.waitFor({ timeout: 20_000 });
    assert((await sectionThree().inputValue()).includes(SENT_CONFLICT), "CONFLICT_LOST_LOCAL_DRAFT");
    await expectText(session, "Unsaved changes", 5_000);
    artifacts.push(await session.screenshot(artifactsDir));
    await conflictDialog.getByRole("button", { name: "View diff against new head" }).click();
    await expectText(session, "SECOND-WRITER SENTINEL", 20_000);
    // Explicit reapply: the draft is re-targeted onto the new head and the
    // server still CAS-checks; full-snapshot semantics keep the second
    // writer's revision (5) durable and immutable in history.
    await session.page.getByRole("button", { name: "Save revision", exact: true }).click();
    await conflictDialog.waitFor({ timeout: 20_000 });
    const headBeforeReapply = (await session.apiFetch(`/api/documents/${docR}`, { expectStatus: 200 })).body.current_revision;
    await conflictDialog.getByRole("button", { name: /Reapply my draft onto revision/ }).click();
    const head6 = await waitHead(session, docR, 6, "REAPPLY_HEAD");
    assert(headBeforeReapply === 5, "REAPPLY_HEAD_ORDER");
    const rev6 = await revisionPayload(session, docR, head6.current_revision_id);
    assert(rev6.sections[2].markdown.includes(SENT_CONFLICT), "REAPPLY_LOST_DRAFT");
    const revisionRows = (await session.apiFetch(`/api/documents/${docR}/revisions`, { expectStatus: 200 })).body?.items ?? [];
    assert(revisionRows[1]?.revision === 5, "REVISION_HISTORY_ORDER");
    const rev5 = await revisionPayload(session, docR, revisionRows[1].id);
    assert(rev5.sections[2].markdown.includes("SECOND-WRITER SENTINEL"), "RACE_REVISION_MUTATED");
    // Stale CAS probe with explicit current-head metadata in the response.
    const staleCas = await session.apiFetch(`/api/documents/${docR}/revisions`, {
      method: "POST",
      body: {
        base_revision_id: docRRev1Id,
        tree: { title: docRDetail.title, sections: [{ heading: "nope", markdown: "nope" }] },
      },
    });
    assert(
      staleCas.status === 409 &&
        staleCas.body?.code === "DOCUMENT_REVISION_CONFLICT" &&
        staleCas.body?.current_head?.revision === 6,
      "STALE_CAS_409",
      String(staleCas.status)
    );
    checks.conflict = { surfaced: true, reapplied: true, stale_cas: "409" };
    artifacts.push(await session.screenshot(artifactsDir));

    /* -- P8: publication — stale head 409, two versions ---------------------- */
    // API publish attempt against a stale expected head: the store rejects a
    // moved expected head with 409 DOCUMENT_REVISION_CONFLICT + current-head
    // metadata (`DOCUMENT_HEAD_MOVED` itself belongs to the completion-time
    // recheck); nothing is published either way.
    const head6Now = (await session.apiFetch(`/api/documents/${docR}`, { expectStatus: 200 })).body;
    const movedPublish = await session.apiFetch(`/api/documents/${docR}/revisions/${head6Now.current_revision_id}/publish`, {
      method: "POST",
      body: { operation_id: randomUUID(), expected_revision_id: docRRev1Id },
    });
    assert(
      movedPublish.status === 409 &&
        movedPublish.body?.code === "DOCUMENT_REVISION_CONFLICT" &&
        movedPublish.body?.current_head?.revision === 6,
      "PUBLISH_STALE_409",
      `${movedPublish.status}/${movedPublish.body?.code}`
    );
    const emptyPubs = await session.apiFetch(`/api/documents/${docR}/publications`, { expectStatus: 200 });
    assert((emptyPubs.body?.items ?? []).length === 0, "STALE_PUBLISH_CREATED_VERSION");
    // Move the head once more through the API, then let the stale UI surface
    // its recovery text, reload, and publish the true head through the UI.
    await session.apiFetch(`/api/documents/${docR}/revisions`, {
      method: "POST",
      body: {
        base_revision_id: head6Now.current_revision_id,
        tree: {
          title: docRDetail.title,
          subtitle: rev6.subtitle,
          verified: rev6.verified,
          sections: [
            rev6.sections[0],
            rev6.sections[1],
            { ...rev6.sections[2], markdown: `${rev6.sections[2].markdown} PRE-PUBLISH SENTINEL` },
          ],
          charts: rev6.charts,
          tables: rev6.tables,
          evidence: rev6.evidence,
        },
      },
      expectStatus: 201,
    });
    await session.page.getByRole("button", { name: "Publish", exact: true }).click();
    await expectText(session, "the document changed since this draft was loaded", 20_000);
    artifacts.push(await session.screenshot(artifactsDir));
    await session.page.reload({ waitUntil: "domcontentloaded" });
    await expectText(session, "Revision 7", 30_000);
    await session.page.getByRole("button", { name: "Publish", exact: true }).click();
    await expectText(session, "latest publication v1", 120_000);
    const pubsV1 = (await session.apiFetch(`/api/documents/${docR}/publications`, { expectStatus: 200 })).body?.items ?? [];
    assert(pubsV1.length === 1 && pubsV1[0].version === 1 && pubsV1[0].supersedes === null, "PUBLISH_V1");
    artifacts.push(await session.screenshot(artifactsDir));

    // Capture v1 export bytes for the immutability check after v2.
    const v1Bytes = {
      html: (await fetchBytes(session, `/api/documents/${docR}/publications/${pubsV1[0].id}/export?format=html`, 200, "RV1")).buffer,
      pdf: (await fetchBytes(session, `/api/documents/${docR}/publications/${pubsV1[0].id}/export?format=pdf`, 200, "RV1")).buffer,
      markdown: (await fetchBytes(session, `/api/documents/${docR}/publications/${pubsV1[0].id}/export?format=markdown`, 200, "RV1")).buffer,
      docx: (await fetchBytes(session, `/api/documents/${docR}/publications/${pubsV1[0].id}/export?format=docx`, 200, "RV1")).buffer,
    };
    const v1Hashes = Object.fromEntries(Object.entries(v1Bytes).map(([k, v]) => [k, sha256(v)]));

    // Publish a second version: one more manual edit, then the real button.
    const ta2 = session.page.getByLabel("Markdown of section 2");
    await ta2.waitFor({ timeout: 10_000 });
    await ta2.click();
    await session.page.keyboard.press("End");
    await session.page.keyboard.type(` ${SENT_V2}`, { delay: 4 });
    await session.page.getByRole("button", { name: "Save revision", exact: true }).click();
    await waitHead(session, docR, 8, "V2_EDIT_HEAD");
    await session.page.getByRole("button", { name: "Publish", exact: true }).click();
    await expectText(session, "latest publication v2", 120_000);
    const pubsR = (await session.apiFetch(`/api/documents/${docR}/publications`, { expectStatus: 200 })).body?.items ?? [];
    assert(
      pubsR.length === 2 && pubsR[0].version === 2 && pubsR[1].version === 1 && pubsR[0].supersedes === pubsR[1].id,
      "PUBLISH_CHAIN"
    );
    checks.publications = { versions: 2, chain: "v2-supersedes-v1" };

    /* -- P9: the chart/evidence-bearing document (first-party tree) --------- */
    //
    // Created through the product's own explicit-tree contract (the same
    // service shape M16 composes). Charts cannot ride the scripted chat turn
    // (see the P2 note); the copy above carries the tables and narrative.
    const appendixLong = "b".repeat(8_100) + "\u{1F642}" + "c".repeat(100);
    const appendixSplit = appendixLong.indexOf("\uD83D\uDE42");
    const docT = (
      await session.apiFetch("/api/documents", {
        method: "POST",
        body: {
          title: DOC_T_TITLE,
          tree: {
            title: DOC_T_TITLE,
            subtitle: "Chart + evidence contract (E2E-C)",
            verified: true,
            sections: [
              { heading: "Summary", markdown: MEMO_V1 },
              { heading: "Numbers", markdown: "June category totals below." },
              { heading: "Appendix", markdown: appendixLong },
            ],
            charts: [{ id: "e2e-c-chart-1", spec: chartSpec }],
            tables: [{ columns: ["category", "transactions", "net_amount"], rows: juneTable }],
            evidence: [
              {
                id: randomUUID(),
                source_id: byName["transactions.csv"].id,
                source_name: "transactions.csv",
                generation: "unknown",
                content_identity: "unknown",
                locator: "June ledger",
                excerpt: `Net groceries ${netText(COMMITTED_EXPECTED.june_groceries_net)} across ${COMMITTED_EXPECTED.june_groceries_tx_count} transactions.`,
              },
            ],
          },
        },
        expectStatus: 201,
      })
    ).body;
    assert(docT.document.current_revision === 1, "DOC_T_CREATED");
    const docTPayload = docT.revision.payload;
    assert(docTPayload.charts.length === 1 && docTPayload.evidence.length === 1, "DOC_T_TREE");
    await goHash(session, `/documents/${docT.document.id}`);
    await expectText(session, "verified origin", 20_000);
    await expectText(session, "unknown provenance", 15_000);
    await expectText(session, "Unresolved citation markers render as plain text", 15_000);
    artifacts.push(await session.screenshot(artifactsDir));

    // Rewrite bounds: the honest 8,000-char UI gate + the server contract.
    // Picking the Appendix in the rewrite section selector (no explicit
    // range) makes the passage the whole 8,203-char section — over the bound
    // — and the UI must say so and refuse to submit.
    session.allowStatuses([400]);
    await session.page.locator("#rewrite-section").selectOption({ value: docTPayload.sections[2].id });
    await expectText(session, `whole section (${appendixLong.length} characters)`, 10_000);
    await expectText(session, "exceeds the 8,000-character bound", 10_000);
    assert(
      await session.page.getByRole("button", { name: "Request rewrite" }).isDisabled(),
      "OVERSIZE_UI_GATE_OPEN"
    );
    const tBase = docT.revision.id;
    const tAppendixId = docTPayload.sections[2].id;
    const tSummaryId = docTPayload.sections[0].id;
    const oversizeRes = await session.apiFetch(`/api/documents/${docT.document.id}/rewrites`, {
      method: "POST",
      body: { base_revision_id: tBase, section_id: tAppendixId, selection_sha256: "0".repeat(64), instruction: "whole oversized section" },
    });
    assert(oversizeRes.status === 400 && oversizeRes.body?.code === "DOCUMENT_REWRITE_SELECTION_OVERSIZE", "OVERSIZE_400", String(oversizeRes.status));
    const badRange = await session.apiFetch(`/api/documents/${docT.document.id}/rewrites`, {
      method: "POST",
      body: { base_revision_id: tBase, section_id: tAppendixId, range_start: 0, range_end: appendixLong.length + 1, selection_sha256: "0".repeat(64), instruction: "out of bounds" },
    });
    assert(badRange.status === 400 && badRange.body?.code === "DOCUMENT_REWRITE_SELECTION_INVALID", "BAD_RANGE_400", String(badRange.status));
    const splitPair = await session.apiFetch(`/api/documents/${docT.document.id}/rewrites`, {
      method: "POST",
      body: {
        base_revision_id: tBase,
        section_id: tAppendixId,
        range_start: appendixSplit,
        range_end: appendixSplit + 1,
        selection_sha256: "0".repeat(64),
        instruction: "split a surrogate pair",
      },
    });
    assert(splitPair.status === 400 && splitPair.body?.code === "DOCUMENT_REWRITE_SELECTION_INVALID", "SURROGATE_400", String(splitPair.status));
    const hashMismatch = await session.apiFetch(`/api/documents/${docT.document.id}/rewrites`, {
      method: "POST",
      body: { base_revision_id: tBase, section_id: tSummaryId, selection_sha256: "f".repeat(64), instruction: "wrong hash" },
    });
    assert(
      hashMismatch.status === 409 && hashMismatch.body?.code === "DOCUMENT_REWRITE_SELECTION_MISMATCH",
      "HASH_MISMATCH_409",
      String(hashMismatch.status)
    );
    checks.rewrite_bounds = ["ui-8000-gate", "oversize-400", "invalid-range-400", "split-surrogate-400", "hash-mismatch-409"];

    // Publish v1 through the API with a known operation UUID (idempotency),
    // capture its frozen export bytes, then edit + publish v2 via the UI.
    const opT1 = randomUUID();
    const publishT1 = await session.apiFetch(`/api/documents/${docT.document.id}/revisions/${tBase}/publish`, {
      method: "POST",
      body: { operation_id: opT1, expected_revision_id: tBase },
      expectStatus: 201,
    });
    assert(publishT1.body.status === "published" && publishT1.body.publication.version === 1, "DOC_T_PUBLISH_V1");
    const publishT1Replay = await session.apiFetch(`/api/documents/${docT.document.id}/revisions/${tBase}/publish`, {
      method: "POST",
      body: { operation_id: opT1, expected_revision_id: tBase },
      expectStatus: 200,
    });
    assert(
      publishT1Replay.body.replayed === true && publishT1Replay.body.publication.id === publishT1.body.publication.id,
      "PUBLISH_OP_REPLAY"
    );
    const tPubs1 = (await session.apiFetch(`/api/documents/${docT.document.id}/publications`, { expectStatus: 200 })).body?.items ?? [];
    assert(tPubs1.length === 1, "PUBLISH_REPLAY_CREATED_VERSION", String(tPubs1.length));
    checks.publish_idempotency = { replayed_same_publication: true };

    const tV1Exports = {
      html: (await fetchBytes(session, `/api/documents/${docT.document.id}/publications/${tPubs1[0].id}/export?format=html`, 200, "TV1")).buffer,
      pdf: (await fetchBytes(session, `/api/documents/${docT.document.id}/publications/${tPubs1[0].id}/export?format=pdf`, 200, "TV1")).buffer,
      markdown: (await fetchBytes(session, `/api/documents/${docT.document.id}/publications/${tPubs1[0].id}/export?format=markdown`, 200, "TV1")).buffer,
      docx: (await fetchBytes(session, `/api/documents/${docT.document.id}/publications/${tPubs1[0].id}/export?format=docx`, 200, "TV1")).buffer,
    };
    const tV1Hashes = Object.fromEntries(Object.entries(tV1Exports).map(([k, v]) => [k, sha256(v)]));
    // v1 content: old memo sentence, exactly one evidence entry, [9] plain.
    const tV1Zip = readZip(tV1Exports.markdown, "TV1");
    assert(
      tV1Zip.has("document.md") && tV1Zip.has("manifest.json") && tV1Zip.has("assets/chart-1.png"),
      "TV1_ZIP_MEMBERS",
      [...tV1Zip.keys()].join(",")
    );
    const tV1Md = tV1Zip.get("document.md").toString("utf8");
    assert(tV1Md.includes(MEMO_V1) && !tV1Md.includes(MEMO_V2), "TV1_MD_NARRATIVE");
    assert(tV1Md.includes("assets/chart-1.png") && !tV1Md.includes(workspace.workspaceDir), "TV1_MD_ASSETS");
    const tV1Manifest = JSON.parse(tV1Zip.get("manifest.json").toString("utf8"));
    assert(
      tV1Manifest.contract === "borealis-document-export/1" &&
        tV1Manifest.publication_version === 1 &&
        tV1Manifest.charts[0]?.file === "assets/chart-1.png" &&
        tV1Manifest.evidence.length === 1 &&
        tV1Manifest.evidence[0].verified === false &&
        tV1Manifest.evidence[0].number === 1,
      "TV1_MANIFEST"
    );
    assert(tV1Md.includes("· provenance unknown") && tV1Md.includes("[9]"), "TV1_MD_EVIDENCE");
    const tV1Docx = readZip(tV1Exports.docx, "TV1");
    assert(tV1Docx.has("[Content_Types].xml") && tV1Docx.has("word/document.xml"), "TV1_DOCX_PARTS");
    const tV1DocXml = tV1Docx.get("word/document.xml").toString("utf8");
    assert(tV1DocXml.includes(MEMO_V1) && tV1DocXml.includes("<w:tbl"), "TV1_DOCX_CONTENT");

    // Revision 2: new memo sentence + a second unknown-provenance reference.
    const docTRev2 = (
      await session.apiFetch(`/api/documents/${docT.document.id}/revisions`, {
        method: "POST",
        body: {
          base_revision_id: tBase,
          tree: {
            title: DOC_T_TITLE,
            subtitle: "Chart + evidence contract (E2E-C)",
            verified: true,
            sections: [
              { id: tSummaryId, heading: "Summary", markdown: MEMO_V2 },
              docTPayload.sections[1],
              docTPayload.sections[2],
            ],
            charts: docTPayload.charts,
            tables: docTPayload.tables,
            evidence: [
              ...docTPayload.evidence,
              {
                id: randomUUID(),
                source_id: byName["budget.csv"].id,
                source_name: "budget.csv",
                generation: "unknown",
                content_identity: "unknown",
                locator: "June budget",
                excerpt: "Budget envelope for June categories.",
              },
            ],
          },
        },
        expectStatus: 201,
      })
    ).body;
    assert(docTRev2.document.current_revision === 2, "DOC_T_REV2");
    await session.page.reload({ waitUntil: "domcontentloaded" });
    await expectText(session, "Revision 2", 30_000);
    await session.page.getByRole("button", { name: "Publish", exact: true }).click();
    await expectText(session, "latest publication v2", 120_000);
    const tPubs = (await session.apiFetch(`/api/documents/${docT.document.id}/publications`, { expectStatus: 200 })).body?.items ?? [];
    assert(tPubs.length === 2 && tPubs[0].version === 2 && tPubs[0].supersedes === tPubs[1].id, "DOC_T_PUBLISH_V2");

    /* -- P10: real browser downloads of all four exports -------------------- */
    const downloadExport = async (rowPosition, label, filenameHint) => {
      const outPath = path.join(exportsDir, filenameHint);
      return downloadVia(
        session,
        () => publicationsRow(session, rowPosition).getByRole("button", { name: label, exact: true }).click(),
        outPath
      );
    };
    // Newest row (position 0) = v2 of the memo document.
    const t2Html = await downloadExport(0, "HTML", "docT-v2.html");
    const t2Pdf = await downloadExport(0, "PDF", "docT-v2.pdf");
    const t2Md = await downloadExport(0, "Markdown", "docT-v2.zip");
    const t2Docx = await downloadExport(0, "DOCX", "docT-v2.docx");

    const t2HtmlText = t2Html.buffer.toString("utf8");
    assertStaticPublicationHtml(t2HtmlText, "DOC_T");
    assert(t2HtmlText.includes("data:image/png"), "DOC_T_HTML_CHART_EMBED");
    assert(t2HtmlText.includes(MEMO_V2) && t2HtmlText.includes("[9]"), "DOC_T_HTML_TEXT");
    assert(t2HtmlText.includes("provenance unknown"), "DOC_T_HTML_EVIDENCE");
    for (const value of juneNets) {
      assert(t2HtmlText.includes(netText(value)), "DOC_T_HTML_TABLE_VALUE", netText(value));
    }
    const t2HtmlHttp = await fetchBytes(session, `/api/documents/${docT.document.id}/publications/${tPubs[0].id}/export?format=html`, 200, "DOC_T");
    assert(t2HtmlHttp.csp.length > 0, "DOC_T_HTML_CSP");
    assert(/nosniff/i.test(t2HtmlHttp.nosniff), "DOC_T_HTML_NOSNIFF");
    assert(/attachment/i.test(t2HtmlHttp.disposition), "DOC_T_HTML_DISPOSITION");

    assertPdf(t2Pdf.buffer, "DOC_T");

    const t2Zip = readZip(t2Md.buffer, "DOC_T");
    assert(
      t2Zip.has("document.md") && t2Zip.has("manifest.json") && t2Zip.has("assets/chart-1.png"),
      "DOC_T_ZIP_MEMBERS",
      [...t2Zip.keys()].join(",")
    );
    assert(PNG_MAGIC.equals(t2Zip.get("assets/chart-1.png").subarray(0, 8)), "DOC_T_ZIP_CHART_PNG_MAGIC");
    const t2MdText = t2Zip.get("document.md").toString("utf8");
    assert(t2MdText.includes(MEMO_V2) && !t2MdText.includes(MEMO_V1), "DOC_T_MD_NARRATIVE");
    assert(t2MdText.includes("assets/chart-1.png") && !/https?:\/\//i.test(t2MdText), "DOC_T_MD_CHART_REF");
    for (const row of juneTable) {
      assert(t2MdText.includes(`| ${row[0]} | ${row[1]} | ${netText(row[2])} |`), "DOC_T_MD_TABLE_ROW", String(row[0]));
    }
    const t2MdManifest = JSON.parse(t2Zip.get("manifest.json").toString("utf8"));
    assert(
      t2MdManifest.publication_version === 2 &&
        t2MdManifest.evidence.length === 2 &&
        t2MdManifest.evidence.every((entry) => entry.verified === false) &&
        JSON.stringify(t2MdManifest.evidence.map((e) => e.number)) === JSON.stringify([1, 2]) &&
        t2MdManifest.assets.includes("assets/chart-1.png"),
      "DOC_T_MANIFEST_V2"
    );
    assert(t2MdText.includes("· provenance unknown") && t2MdText.includes("[9]"), "DOC_T_MD_EVIDENCE");

    const t2DocxZip = readZip(t2Docx.buffer, "DOC_T");
    assert(t2DocxZip.has("[Content_Types].xml") && t2DocxZip.has("word/document.xml"), "DOC_T_DOCX_PARTS");
    const t2DocXml = t2DocxZip.get("word/document.xml").toString("utf8");
    assert(t2DocXml.includes(MEMO_V2), "DOC_T_DOCX_NARRATIVE");
    assert(t2DocXml.includes("<w:tbl"), "DOC_T_DOCX_TABLE");
    for (const value of juneNets) {
      assert(t2DocXml.includes(netText(value)), "DOC_T_DOCX_TABLE_VALUE", netText(value));
    }
    const t2DocxMedia = [...t2DocxZip.keys()].filter((name) => /^word\/media\/[^/]+\.png$/i.test(name));
    assert(t2DocxMedia.length >= 1 && PNG_MAGIC.equals(t2DocxZip.get(t2DocxMedia[0]).subarray(0, 8)), "DOC_T_DOCX_MEDIA_PNG", t2DocxMedia[0]);
    // No external targets (OOXML namespace URIs like
    // http://schemas.openxmlformats.org/... are identifiers, not fetches;
    // only TargetMode="External" or an external Target is a remote ref).
    const t2Rels = [...t2DocxZip.keys()].filter((name) => name.endsWith(".rels")).map((name) => t2DocxZip.get(name).toString("utf8"));
    assert(
      !t2Rels.some((rels) => /TargetMode="External"/i.test(rels) || /Target="https?:/i.test(rels)),
      "DOC_T_DOCX_EXTERNAL_REF"
    );
    checks.exports_doc_t = { html: t2Html.buffer.length, pdf: t2Pdf.buffer.length, md_members: t2Zip.size, docx: t2Docx.buffer.length };

    // The older version re-downloaded through the UI must be byte-identical.
    const t1HtmlAgain = await downloadExport(1, "HTML", "docT-v1-after-v2.html");
    const t1PdfAgain = await downloadExport(1, "PDF", "docT-v1-after-v2.pdf");
    const t1MdAgain = await downloadExport(1, "Markdown", "docT-v1-after-v2.zip");
    assert(sha256(t1HtmlAgain.buffer) === tV1Hashes.html, "DOC_T_V1_HTML_MUTATED");
    assert(sha256(t1PdfAgain.buffer) === tV1Hashes.pdf, "DOC_T_V1_PDF_MUTATED");
    assert(sha256(t1MdAgain.buffer) === tV1Hashes.markdown, "DOC_T_V1_MD_MUTATED");
    const t1MdAfter = readZip(t1MdAgain.buffer, "DOC_T_V1").get("document.md").toString("utf8");
    assert(t1MdAfter.includes(MEMO_V1) && !t1MdAfter.includes(MEMO_V2), "DOC_T_V1_NARRATIVE_MUTATED");
    assert(!t1MdAfter.includes("Budget envelope"), "DOC_T_V1_EVIDENCE_MUTATED");
    const t1DocxHttp = await fetchBytes(session, `/api/documents/${docT.document.id}/publications/${tPubs[1].id}/export?format=docx`, 200, "TV1DOCX");
    assert(sha256(t1DocxHttp.buffer) === tV1Hashes.docx, "DOC_T_V1_DOCX_MUTATED");
    // Chart/evidence are revision-bound: the frozen canonical chart + table
    // payloads are byte-identical across the published revisions while the
    // narrative and evidence numbering differ per revision.
    const tR1 = await revisionPayload(session, docT.document.id, tBase);
    const tR2 = await revisionPayload(session, docT.document.id, docTRev2.revision.id);
    assert(
      JSON.stringify(tR1.charts) === JSON.stringify(tR2.charts) &&
        JSON.stringify(tR1.tables) === JSON.stringify(tR2.tables) &&
        tR1.sections[0].markdown !== tR2.sections[0].markdown &&
        tR1.evidence.length === 1 &&
        tR2.evidence.length === 2,
      "DOC_T_REVISION_BINDING"
    );
    artifacts.push(await session.screenshot(artifactsDir));

    /* -- P10b: the copy's own two publications + four real downloads -------- */
    await goHash(session, `/documents/${docR}`);
    await expectText(session, "latest publication v2", 20_000);
    const rHtml = await downloadExport(0, "HTML", "docR-v2.html");
    await downloadExport(0, "PDF", "docR-v2.pdf");
    const rMd = await downloadExport(0, "Markdown", "docR-v2.zip");
    const rDocx = await downloadExport(0, "DOCX", "docR-v2.docx");
    const rHtmlText = rHtml.buffer.toString("utf8");
    assertStaticPublicationHtml(rHtmlText, "DOC_R");
    assert(rHtmlText.includes(REPL_2) && rHtmlText.includes(SENT_V2), "DOC_R_HTML_TEXT");
    assert(rHtmlText.includes("Unverified document — manual claims, no evidence references"), "DOC_R_VALIDITY_LINE");
    const rZip = readZip(rMd.buffer, "DOC_R");
    assert(rZip.has("document.md") && rZip.has("manifest.json"), "DOC_R_ZIP_MEMBERS");
    const rMdText = rZip.get("document.md").toString("utf8");
    for (const row of juneTable) {
      assert(rMdText.includes(`| ${row[0]} | ${row[1]} | ${netText(row[2])} |`), "DOC_R_MD_TABLE_ROW", String(row[0]));
    }
    const rDocxZip = readZip(rDocx.buffer, "DOC_R");
    const rDocXml = rDocxZip.get("word/document.xml").toString("utf8");
    assert(
      rDocXml.includes(REPL_2) && rDocXml.includes("<w:tbl") && rDocXml.includes(netText(COMMITTED_EXPECTED.june_groceries_net)),
      "DOC_R_DOCX_CONTENT"
    );
    // v1 of the copy must still serve its frozen bytes (captured at P8).
    assert(
      sha256((await fetchBytes(session, `/api/documents/${docR}/publications/${pubsR[1].id}/export?format=html`, 200, "RV1AFTER")).buffer) === v1Hashes.html,
      "DOC_R_V1_HTML_MUTATED"
    );
    assert(
      sha256((await fetchBytes(session, `/api/documents/${docR}/publications/${pubsR[1].id}/export?format=pdf`, 200, "RV1AFTER")).buffer) === v1Hashes.pdf,
      "DOC_R_V1_PDF_MUTATED"
    );
    assert(
      sha256((await fetchBytes(session, `/api/documents/${docR}/publications/${pubsR[1].id}/export?format=markdown`, 200, "RV1AFTER")).buffer) === v1Hashes.markdown,
      "DOC_R_V1_MD_MUTATED"
    );
    assert(
      sha256((await fetchBytes(session, `/api/documents/${docR}/publications/${pubsR[1].id}/export?format=docx`, 200, "RV1AFTER")).buffer) === v1Hashes.docx,
      "DOC_R_V1_DOCX_MUTATED"
    );
    checks.exports_doc_r = { versions: pubsR.length, downloads: ["html", "pdf", "markdown", "docx"] };

    /* -- P11: closed dialogs leak nothing (duplicate template name) --------- */
    await session.page.getByRole("button", { name: "Save as template" }).click();
    const templateDialog = session.page.getByRole("dialog", { name: "Save structure as template" });
    await templateDialog.waitFor({ timeout: 10_000 });
    await session.page.locator("#template-name").fill("C layout (E2E-C)");
    await session.page.getByRole("button", { name: "Save template", exact: true }).click();
    await expectText(session, "Template saved. You can apply it to a new document from the Documents page.", 15_000);
    await templateDialog.getByRole("button", { name: "Close", exact: true }).click();
    await pollUntil(
      async () => (await templateDialog.count()) === 0,
      { deadlineMs: 10_000, intervalMs: 150 }
    ).then((closed) => assert(closed === true, "TEMPLATE_DIALOG_NOT_CLOSED"));
    // Reopening shows a fresh dialog: the old success slot never leaks.
    await session.page.getByRole("button", { name: "Save as template" }).click();
    await templateDialog.waitFor({ timeout: 10_000 });
    assert(!(await templateDialog.getByText("Template saved.").isVisible().catch(() => false)), "STALE_TEMPLATE_SUCCESS");
    await session.page.locator("#template-name").fill("C layout (E2E-C)");
    await session.page.getByRole("button", { name: "Save template", exact: true }).click();
    await expectText(session, "already exists", 15_000);
    assert((await templateDialog.isVisible()) === true, "TEMPLATE_ERROR_CLOSED_DIALOG");
    await templateDialog.getByRole("button", { name: "Cancel", exact: true }).click();
    await pollUntil(
      async () => (await templateDialog.count()) === 0,
      { deadlineMs: 10_000, intervalMs: 150 }
    ).then((closed) => assert(closed === true, "TEMPLATE_ERROR_DIALOG_STUCK"));
    assert(!(await session.page.locator('[role="alert"]').first().isVisible().catch(() => false)), "TEMPLATE_ERROR_LEAKED_TO_PAGE");
    artifacts.push(await session.screenshot(artifactsDir));
    checks.dialog_lifecycle = "fresh-on-reopen; error contained in dialog";

    /* -- P11b: foreign account + share-recipient denial ---------------------- */
    sessionForeign = await browser.newSession({ origin: server.origin });
    await sessionForeign.register({ email: EMAIL_B, password: `${PASSWORD}-b` });
    sessionForeign.allowStatuses([404]);
    const foreignDocs = await sessionForeign.apiFetch("/api/documents", { expectStatus: 200 });
    assert((foreignDocs.body?.items ?? []).length === 0, "FOREIGN_DOCUMENT_CATALOG");
    const foreignDoc = await sessionForeign.apiFetch(`/api/documents/${docR}`);
    assert(foreignDoc.status === 404 && foreignDoc.body?.code === "DOCUMENT_NOT_FOUND", "FOREIGN_DOCUMENT_404");
    const foreignExport = await sessionForeign.apiFetchText(`/api/documents/${docR}/publications/${pubsR[0].id}/export?format=html`);
    assert(foreignExport.status === 404, "FOREIGN_EXPORT_404", String(foreignExport.status));
    const foreignCopy = await sessionForeign.apiFetch("/api/documents", { method: "POST", body: { copy_from_report_id: reportId } });
    assert(foreignCopy.status === 404, "FOREIGN_COPY_404", String(foreignCopy.status));

    const accounts = (await session.apiFetch("/api/accounts", { expectStatus: 200 })).body ?? [];
    const recipient = accounts.find((account) => account.email === EMAIL_B);
    assert(recipient !== undefined, "RECIPIENT_ACCOUNT");
    await session.apiFetch(`/api/reports/${reportId}/shares`, {
      method: "POST",
      body: { recipient_account_id: recipient.id },
      expectStatus: 201,
    });
    const sharedDetail = await sessionForeign.apiFetch(`/api/reports/${reportId}`, { expectStatus: 200 });
    assert(sharedDetail.body?.shared_by_account === true, "SHARED_FLAG");
    assert(!("payload" in sharedDetail.body), "SHARED_PAYLOAD_LEAK");
    const recipientCopy = await sessionForeign.apiFetch("/api/documents", { method: "POST", body: { copy_from_report_id: reportId } });
    assert(recipientCopy.status === 404, "RECIPIENT_COPY_404", String(recipientCopy.status));
    checks.access = { foreign_404: true, shared_payload_omitted: true, recipient_copy_denied: true };

    /* -- P12: full backend restart — durable document state ----------------- */
    const preRestart = {
      docR: (await session.apiFetch(`/api/documents/${docR}`, { expectStatus: 200 })).body,
      revisions: (await session.apiFetch(`/api/documents/${docR}/revisions`, { expectStatus: 200 })).body.items.map(
        (e) => [e.revision, e.author_kind, e.published_version]
      ),
      publications: (await session.apiFetch(`/api/documents/${docR}/publications`, { expectStatus: 200 })).body.items.map(
        (e) => [e.version, e.revision, e.supersedes]
      ),
      tPublications: (await session.apiFetch(`/api/documents/${docT.document.id}/publications`, { expectStatus: 200 })).body.items.map(
        (e) => [e.version, e.revision]
      ),
      rewriteCount: (await session.apiFetch(`/api/documents/${docR}/rewrites`, { expectStatus: 200 })).body.items.length,
    };
    const restartInfo = await server.restart({ token: await session.token() });
    assert(typeof restartInfo.pid === "number", "RESTART_PID");
    const postRestartDoc = (await session.apiFetch(`/api/documents/${docR}`, { expectStatus: 200 })).body;
    assert(
      postRestartDoc.current_revision === preRestart.docR.current_revision &&
        postRestartDoc.latest_publication_version === preRestart.docR.latest_publication_version,
      "RESTART_DOCUMENT_HEAD_DRIFT"
    );
    assert(
      JSON.stringify(
        (await session.apiFetch(`/api/documents/${docR}/revisions`, { expectStatus: 200 })).body.items.map((e) => [
          e.revision,
          e.author_kind,
          e.published_version,
        ])
      ) === JSON.stringify(preRestart.revisions),
      "RESTART_REVISION_HISTORY_DRIFT"
    );
    assert(
      JSON.stringify(
        (await session.apiFetch(`/api/documents/${docR}/publications`, { expectStatus: 200 })).body.items.map((e) => [
          e.version,
          e.revision,
          e.supersedes,
        ])
      ) === JSON.stringify(preRestart.publications),
      "RESTART_PUBLICATION_HISTORY_DRIFT"
    );
    assert(
      JSON.stringify(
        (await session.apiFetch(`/api/documents/${docT.document.id}/publications`, { expectStatus: 200 })).body.items.map((e) => [
          e.version,
          e.revision,
        ])
      ) === JSON.stringify(preRestart.tPublications),
      "RESTART_DOC_T_PUBLICATION_DRIFT"
    );
    assert(
      (await session.apiFetch(`/api/documents/${docR}/rewrites`, { expectStatus: 200 })).body.items.length ===
        preRestart.rewriteCount,
      "RESTART_REWRITE_HISTORY_DRIFT"
    );
    // Frozen export bytes + the legacy report bytes survive the restart.
    assert(
      sha256(
        (await fetchBytes(session, `/api/documents/${docT.document.id}/publications/${tPubs[0].id}/export?format=html`, 200, "POST")).buffer
      ) === sha256(t2Html.buffer),
      "RESTART_EXPORT_BYTES_DRIFT"
    );
    const legacyAfterRestart = await fetchBytes(session, `/api/reports/${reportId}/html`, 200, "LEGACY");
    assert(sha256(legacyAfterRestart.buffer) === legacyHashes.html, "LEGACY_HTML_CHANGED_EVER");
    const chatAfterRestart = (await session.apiFetch(`/api/chats/${chatId}`, { expectStatus: 200 })).body;
    const assistantAfterRestart = (chatAfterRestart.messages ?? []).find((m) => m.role === "assistant" && m.meta?.report);
    assert(
      assistantAfterRestart !== undefined && JSON.stringify(assistantAfterRestart.meta) === chatMetaSnapshot,
      "CHAT_ARTIFACT_META_DRIFT"
    );
    // The workbench still renders after the restart.
    await goHash(session, `/documents/${docT.document.id}`);
    await expectText(session, "latest publication v2", 30_000);
    artifacts.push(await session.screenshot(artifactsDir));
    checks.restart = { durable: true };

    /* -- skipped sub-check (recorded honestly) ------------------------------ */
    checks.skipped = [
      "payload-less legacy report unreachable under scripted acceptance (product persists reports only via completed agent turns; payload drops above 400k serialized chars while tool args cap at 20k chars and the provider script body at 256 KiB; no delete-payload API) — owner-only copy denial + payload-less recipient view exercised instead",
      "chart reference inside the scripted chat report (provider fixture has no tool-result echo; chart ids are run-scoped random UUIDs) — chart-bearing document contract exercised via the first-party tree-creation route",
    ];

    /* -- wrap up ------------------------------------------------------------- */
    await server.quiesceWorkers({ token: await session.token() });
    session.assertClean();
    sessionForeign.assertClean();

    return { artifacts, checks };
  } catch (error) {
    // Failure triage without touching the harness summary contract: stable
    // codes ride in the summary; this file keeps the selector/route detail.
    await fs.promises.writeFile(
      path.join(artifactsDir, "debug-failure.txt"),
      String(error?.stack ?? error?.message ?? error).slice(0, 1_500)
    ).catch(() => undefined);
    await session.screenshot(artifactsDir).then((name) => artifacts.push(name)).catch(() => "shot-failed.png");
    throw error;
  } finally {
    await session.close().catch(() => undefined);
    await sessionForeign?.close().catch(() => undefined);
  }
}
