import { memo, useEffect, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeHighlight from "rehype-highlight";
import { Bot, User, FileText, ExternalLink } from "lucide-react";
import { cn } from "@/lib/utils";
import { openProtected, reportsApi } from "@/lib/api";
import { ChartCard } from "@/components/ChartCard";

function ReportLink({ reportId }: { reportId: string }) {
  const [info, setInfo] = useState<{ title: string; hasHtml: boolean; hasPdf: boolean } | null>(null);
  const [err, setErr] = useState(false);
  useEffect(() => {
    reportsApi
      .get(reportId)
      .then((r) => setInfo({ title: r.title, hasHtml: r.has_html, hasPdf: r.has_pdf }))
      .catch(() => setErr(true));
  }, [reportId]);
  const title = info?.title || "Report";
  return (
    <div className="mt-3 flex flex-wrap items-center gap-2 rounded-xl border border-aurora-teal/20 bg-gradient-to-r from-aurora-teal/10 to-aurora-violet/10 p-3">
      <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-gradient-to-br from-aurora-teal to-aurora-violet text-aurora-foreground">
        <FileText className="h-5 w-5" />
      </div>
      <div className="min-w-0 flex-1">
        <div className="truncate text-sm font-semibold text-foreground">{title}</div>
        <div className="text-xs text-muted-foreground">Generated by Borealis · HTML + PDF</div>
      </div>
      {info?.hasHtml && (
        <button
          onClick={() => openProtected("html", `/api/reports/${reportId}/html`, `${title}.html`)}
          className="inline-flex h-8 items-center gap-1.5 rounded-md border bg-card/60 px-3 text-xs font-medium text-foreground transition-colors hover:border-aurora-teal/50 hover:text-aurora-teal focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
        >
          <ExternalLink className="h-3.5 w-3.5" /> View HTML
        </button>
      )}
      {info?.hasPdf && (
        <button
          onClick={() => openProtected("pdf", `/api/reports/${reportId}/pdf`, `${title}.pdf`)}
          className="inline-flex h-8 items-center gap-1.5 rounded-md bg-gradient-to-r from-aurora-teal to-aurora-blue px-3 text-xs font-semibold text-aurora-foreground transition-opacity hover:opacity-90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
        >
          Download PDF
        </button>
      )}
      {err && <span className="text-xs text-muted-foreground">Report expired</span>}
    </div>
  );
}

export const ChatMessage = memo(function ChatMessage({
  role,
  content,
  reasoning,
  charts,
  report,
  model,
  streaming,
  className,
}: {
  role: "user" | "assistant";
  content: string;
  reasoning?: string;
  charts?: string[];
  report?: string | null;
  model?: string;
  streaming?: boolean;
  className?: string;
}) {
  const isUser = role === "user";
  return (
    <div className={cn("group flex w-full gap-3", isUser ? "justify-end" : "justify-start", className)}>
      {!isUser && (
        <div className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-aurora-teal to-aurora-violet shadow">
          <Bot className="h-[18px] w-[18px] text-aurora-foreground" />
        </div>
      )}
      <div className={cn("max-w-[78%] md:max-w-[70%]", isUser ? "items-end text-right" : "items-start")}>
        {isUser ? (
          <div className="inline-block whitespace-pre-wrap rounded-2xl rounded-tr-md bg-secondary px-4 py-3 text-[15px] leading-relaxed text-secondary-foreground">
            {content}
          </div>
        ) : (
          <div className="rounded-2xl rounded-tl-md text-[15px] leading-relaxed text-foreground/90">
            {reasoning && (
              <details className="mb-3 rounded-lg border bg-surface-subtle px-3 py-2 text-sm text-muted-foreground">
                <summary className="cursor-pointer select-none font-medium text-foreground/80">Thought process</summary>
                <div className="mt-2 whitespace-pre-wrap text-xs leading-relaxed">{reasoning}</div>
              </details>
            )}
            <div className="markdown-body">
              <ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeHighlight]}>
                {content || (streaming ? "" : "_no response_")}
              </ReactMarkdown>
            </div>
            {model && (
              <div className="mt-2 flex min-w-0 items-center gap-1.5 text-[10px] text-muted-foreground">
                <span>Model</span>
                <span className="truncate font-mono text-foreground/70" title={model}>
                  {model}
                </span>
              </div>
            )}
            {streaming && !content && (
              <div className="mt-2 flex gap-1.5 py-1">
                {[0, 1, 2].map((i) => (
                  <span
                    key={i}
                    className="h-2 w-2 rounded-full bg-aurora-teal"
                    style={{ animation: `aurora-pulse 1.2s ${i * 0.2}s infinite` }}
                  />
                ))}
              </div>
            )}
            {charts && charts.length > 0 && (
              <div className="mt-2 space-y-3">
                {charts.map((id) => (
                  <ChartCard key={id} chartId={id} />
                ))}
              </div>
            )}
            {report && <ReportLink reportId={report} />}
          </div>
        )}
      </div>
      {isUser && (
        <div className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-secondary">
          <User className="h-[16px] w-[16px] text-muted-foreground" />
        </div>
      )}
    </div>
  );
});
