import { lazy, memo, Suspense, useEffect, useMemo, useState, type ReactNode } from "react";
import ReactMarkdown, { defaultUrlTransform } from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeHighlight from "rehype-highlight";
import { Bot, User, FileText, ExternalLink } from "lucide-react";
import { cn } from "@/lib/utils";
import {
  openProtected,
  formatApiError,
  reportsApi,
  type CitationRef,
  type QueryResultArtifact,
  type RetrievedEvidence as RetrievedEvidenceItem,
} from "@/lib/api";
import { citeLinkify, parseCiteHref } from "@/lib/citations";
import { DataResultCard } from "@/components/DataResultCard";
import { LazyLoadBoundary } from "@/components/LazyLoadBoundary";
import { RetrievedEvidence } from "@/components/RetrievedEvidence";

const ChartCard = lazy(() => import("@/components/ChartCard").then((module) => ({ default: module.ChartCard })));

function ChartFallback() {
  return (
    <div className="embedded-chart space-y-2 py-4" role="status" aria-label="Loading chart">
      <div className="h-4 w-1/3 animate-pulse rounded bg-secondary" />
      <div className="h-52 w-full animate-pulse rounded bg-secondary" />
    </div>
  );
}

function ReportLink({ reportId }: { reportId: string }) {
  const [info, setInfo] = useState<{ title: string; hasHtml: boolean; hasPdf: boolean } | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busyKind, setBusyKind] = useState<"html" | "pdf" | null>(null);
  useEffect(() => {
    let active = true;
    setInfo(null);
    setError(null);
    reportsApi
      .get(reportId)
      .then((report) => {
        if (active) setInfo({ title: report.title, hasHtml: report.has_html, hasPdf: report.has_pdf });
      })
      .catch((failure: unknown) => {
        if (active) setError(formatApiError(failure, "Report unavailable"));
      });
    return () => {
      active = false;
    };
  }, [reportId]);
  const title = info?.title || "Report";
  const openReport = async (kind: "html" | "pdf") => {
    setError(null);
    setBusyKind(kind);
    try {
      await openProtected(kind, `/api/reports/${reportId}/${kind}`, `${title}.${kind}`);
    } catch (failure: unknown) {
      setError(formatApiError(failure, `Could not open the report ${kind.toUpperCase()}`));
    } finally {
      setBusyKind(null);
    }
  };
  const formats = info ? [info.hasHtml ? "HTML" : null, info.hasPdf ? "PDF" : null].filter(Boolean) : [];
  return (
    <div className="mt-3 flex flex-wrap items-center gap-2 rounded-lg border border-primary/25 bg-surface-subtle p-3">
      <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary text-primary-foreground">
        <FileText className="h-5 w-5" />
      </div>
      <div className="min-w-0 flex-1">
        <div className="truncate text-sm font-semibold text-foreground">{title}</div>
        <div className="text-xs text-muted-foreground">
          {info
            ? formats.length > 0
              ? `Generated by Borealis · ${formats.join(" + ")}`
              : "Artifacts unavailable"
            : "Generated by Borealis"}
        </div>
      </div>
      {info?.hasHtml && (
        <button
          onClick={() => void openReport("html")}
          disabled={busyKind !== null}
          className="inline-flex h-8 items-center gap-1.5 rounded-md border bg-card px-3 text-xs font-medium text-foreground transition-colors hover:border-primary/50 hover:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-wait disabled:opacity-60"
        >
          <ExternalLink className="h-3.5 w-3.5" /> View HTML
        </button>
      )}
      {info?.hasPdf && (
        <button
          onClick={() => void openReport("pdf")}
          disabled={busyKind !== null}
          className="inline-flex h-8 items-center gap-1.5 rounded-md bg-primary px-3 text-xs font-semibold text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:cursor-wait disabled:opacity-60"
        >
          Download PDF
        </button>
      )}
      {error && (
        <span className="w-full text-xs text-destructive" role="alert">
          {error}
        </span>
      )}
    </div>
  );
}

export const ChatMessage = memo(function ChatMessage({
  role,
  content,
  charts,
  report,
  model,
  evidence,
  citations,
  queryResults,
  streaming,
  className,
}: {
  role: "user" | "assistant";
  content: string;
  charts?: string[];
  report?: string | null;
  model?: string;
  evidence?: RetrievedEvidenceItem[];
  citations?: CitationRef[];
  queryResults?: QueryResultArtifact[];
  streaming?: boolean;
  className?: string;
}) {
  const isUser = role === "user";
  // Citation chips open the evidence panel, so that state lives here.
  const [evidenceOpen, setEvidenceOpen] = useState(false);
  const [highlightCitation, setHighlightCitation] = useState<number | null>(null);

  // meta.citations is authoritative when present; rows that predate it fall
  // back to numbering the evidence array itself. Every candidate stays
  // fail-closed against the evidence passage it must be able to open.
  const validCitations = useMemo(() => {
    const numbers = new Set<number>();
    if (!evidence || evidence.length === 0) return numbers;
    if (citations && citations.length > 0) {
      for (const citation of citations) {
        if (Number.isSafeInteger(citation.n) && citation.n >= 1 && citation.n <= evidence.length) {
          numbers.add(citation.n);
        }
      }
    } else {
      for (let n = 1; n <= evidence.length; n += 1) numbers.add(n);
    }
    return numbers;
  }, [citations, evidence]);

  const displayContent = validCitations.size > 0 ? citeLinkify(content, validCitations) : content;

  const citationSource = (n: number): string => {
    const citation = citations?.find((entry) => entry.n === n);
    return citation?.source || evidence?.[n - 1]?.source || "source";
  };

  const openCitation = (n: number) => {
    setHighlightCitation(n);
    setEvidenceOpen(true);
  };

  // cite:// hrefs come from citeLinkify, but the model can also emit raw
  // `[n](cite://n)` markdown. Only resolvable citations become chips; every
  // other cite:// href stays inert text instead of a dead link.
  const renderAnchor = ({ href, children }: { href?: string; children?: ReactNode }) => {
    const n = typeof href === "string" ? parseCiteHref(href) : null;
    if (n === null) return <a href={href}>{children}</a>;
    if (!validCitations.has(n)) return <span>{children}</span>;
    return (
      <button
        type="button"
        onClick={() => openCitation(n)}
        aria-label={`Citation ${n}: ${citationSource(n)}`}
        className="mx-0.5 inline-flex h-4 min-w-4 cursor-pointer items-center justify-center rounded-full bg-primary/10 px-1 align-super text-[10px] font-semibold leading-none text-primary transition-colors hover:bg-primary/20 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
      >
        {n}
      </button>
    );
  };

  return (
    <div className={cn("group flex w-full gap-3", isUser ? "justify-end" : "justify-start", className)}>
      {!isUser && (
        <div className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-primary shadow-sm">
          <Bot className="h-[18px] w-[18px] text-primary-foreground" />
        </div>
      )}
      <div className={cn("max-w-[78%] md:max-w-[70%]", isUser ? "items-end text-right" : "items-start")}>
        {isUser ? (
          <div className="inline-block whitespace-pre-wrap rounded-lg rounded-tr-sm bg-secondary px-4 py-3 text-[15px] leading-relaxed text-secondary-foreground">
            {content}
          </div>
        ) : (
          <div className="rounded-lg rounded-tl-sm text-[15px] leading-relaxed text-foreground/90">
            <div className="markdown-body">
              <ReactMarkdown
                remarkPlugins={[remarkGfm]}
                rehypePlugins={[rehypeHighlight]}
                // The default URL sanitizer strips the cite:// scheme; allow
                // only well-formed citation hrefs through and keep default
                // sanitization for every other URL.
                urlTransform={(url) =>
                  typeof url === "string" && parseCiteHref(url) !== null ? url : defaultUrlTransform(url)
                }
                components={{ a: renderAnchor }}
              >
                {displayContent || (streaming ? "" : "_no response_")}
              </ReactMarkdown>
            </div>
            {evidence && evidence.length > 0 && (
              <RetrievedEvidence
                evidence={evidence}
                open={evidenceOpen}
                onOpenChange={setEvidenceOpen}
                highlightN={highlightCitation}
              />
            )}
            {queryResults && queryResults.length > 0 && (
              <div className="mt-3 space-y-3">
                {queryResults.map((artifact, index) => (
                  <DataResultCard key={`${artifact.id}-${index}`} artifact={artifact} index={index} />
                ))}
              </div>
            )}
            {model && (
              <div className="mt-2 flex min-w-0 items-center gap-1.5 text-[10px] text-muted-foreground">
                <span>Model</span>
                <span className="truncate font-mono text-foreground/70" title={model}>
                  {model}
                </span>
              </div>
            )}
            {streaming && !content && (
              <div className="mt-2 flex gap-1.5 py-1">
                {[0, 1, 2].map((i) => (
                  <span
                    key={i}
                    className="h-2 w-2 animate-status-pulse rounded-full bg-primary"
                    style={{ animationDelay: `${i * 0.2}s` }}
                  />
                ))}
              </div>
            )}
            {charts && charts.length > 0 && (
              <div className="mt-2 space-y-3">
                {charts.map((id) => (
                  <LazyLoadBoundary key={id} label="This chart" resetKey={id}>
                    <Suspense fallback={<ChartFallback />}>
                      <ChartCard chartId={id} />
                    </Suspense>
                  </LazyLoadBoundary>
                ))}
              </div>
            )}
            {report && <ReportLink reportId={report} />}
          </div>
        )}
      </div>
      {isUser && (
        <div className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-secondary">
          <User className="h-[16px] w-[16px] text-muted-foreground" />
        </div>
      )}
    </div>
  );
});
